name: Charmed Operator Log Dump
description: >
  Print out logs and metadata to assist you in troubleshooting charm issues.
inputs:
  model:
    default: testing
    description: |
      The name of the model you want to print the info for, for instance
      `testing` or `lma`.
  app:
    required: true
    description: |
      The label of the application you want to print logs for, for instance
      "minio" or "prometheus".
  operator:
    default: modeloperator
    description: |
      The label of the Juju operator pod to print the info for.  Defaults
      to `modeloperator`, which is the model operator.
  
runs:
  using: "composite"
  steps:
    - name: Get all
      run: sudo kubectl get all -A
      shell: bash

    - name: Describe deployments
      run: |
        sudo kubectl describe \
          deployments -A
      shell: bash

    - name: Describe replicasets
      run: |
        sudo kubectl describe \
          replicasets -A
      shell: bash

    - name: Get juju status
      run: juju status
      shell: bash

    - name: Get application charm logs
      run: |
        sudo kubectl logs \
          -n ${{ inputs.model }} \
          --all-containers \
          --tail 1000 \
          --selector app.kubernetes.io/name=${{ inputs.app }}
      shell: bash
    - name: Get operator controller logs
      run: |
        sudo kubectl logs \
          -n ${{ inputs.model }} \
          --tail 1000 \
          --selector operator.juju.is/name=${{ inputs.operator }}
      shell: bash
